node('basic-node-0') {
    def random = new Random()
    stage('Precheck') {
        print('Checking things out.')
    }

    stage('Build') {
        print('Building things.')
    }

    stage('Testing') {
        parallel(
            'Xenial': {
                print(random.nextInt())
                print('Testing xenial!')
            },
            'Windows': {
                print(random.nextInt())
                print('Testing Windows!')
            }
        )
    }
}